version: '3.7'

services:
  monitor:
    image: wildsong/arctic-monitor
    environment:
      LICENSE: /home/flexlm/service.txt
      VIRTUAL_PORT: 5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 5000:5000
    restart: unless=stopped
